### ISSUE TITLE
Stop if no SQL is received

### ISSUE THREAD

**Issue by JacobNeergaard** [TRP-Solutions/dbtool#53]
No sql file on commandline will drop all tables if not carefull

**Comment by JacobNeergaard** [comment]
<img width="1594" alt="Screenshot 2022-11-09 at 19 42 16" src="https://user-images.githubusercontent.com/24679577/201341924-5edebfc4-30ae-4447-b042-c57e17305320.png">

**Comment by Zatnosk** [comment]
fixed in 3d1430b67db209537a16432af2ec28c54d4b9bd2
